### ISSUE TITLE
no command nu-completions

### ISSUE THREAD

**Issue by Mehdi-YC** [dscottboggs/nu-completions#4]
i don't know if something is wrong or i have a wrong version but i get this error 
![image](https://github.com/dscottboggs/nu-completions/assets/44881216/df2faff1-7400-4b10-8178-523080720686)

**Comment by dscottboggs** [comment]
I think I'm going to abandon this project. Man pages are inconsistent across distributions, even for packages that are the same version. Whether you go all overboard like this and try to track a patch set, or just generate the completions once and track those completion files, you're stuck tracking changes to man pages in some way or another *constantly* for ***every*** *distro*.

Even if you do manage to put together enough people to do that thankless work and manage to get this overengineered solution to be robust and less klunky, there's another problem: nu takes about 1 second to load 1000 completion files on launch, meaning that launching my shell took at least 4.5-5 seconds every time. I put up with this for a little while, but then realized in a near-OOM situation I had no way to get to a shell that would open without compounding the problem by a lot.

I think that I'll probably be trying out [these instructions](http://www.nushell.sh/book/custom_completions.html#external-completions) for setting up Carapace for completions next time I need to scratch this itch. If I'm being honest, this experience has soured me a bit on nushell in general.

-----

In answer to your specific question, I think it's called `nu-completions-script` now for some reason, I forget why. If you actually want to use this thing you'll probably need to be familiar enough with the source code to find out what the actual name is anyway.

**Comment by Mehdi-YC** [comment]
didn't distrotube recently talked about this ? this is a problem ,

but also giving standards will make linux look like a corporation rather than opensource this is the problem

**Comment by dscottboggs** [comment]
I'm not sure I understand you, but sometimes standardization without enforcement or coercion is the best way to go about things. I'm not saying it's not unfortunate that this is a problem, I just think there is some upstream work that needs done before this solution or one like it is viable. I do hope that it can serve as a way to help guide that development and help people learn some lessons about this goal, but the scope has gone beyond what I initially expected or have the capacity for, unfortunately.

**Comment by Mehdi-YC** [comment]
yes actually maybe even better , a markup language that can be used across all shells
like writing it in yaml could ve great
